config/routes.rb
CfoApp::Application.routes.draw do
 
  get '/home', to: 'welcome#home'
  get '/required', to: 'work#required'
  get '/faq', to: 'work#faq'
  get '/articles', to: 'work#articles'
  get '/contact', to: 'work#contact'
  
  get '/services', to: 'welcome#services'
  get '/about', to: 'welcome#about'

  resources :users

  

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def services
  end

  def about
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
  def required
  end

  def faq
  end

  def articles
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/layouts/_header.html.erb
      <div class="masthead">
        <h3 class="muted">CFO Support</h3>
        <div class="navbar navbar-fixed-top navbar-inverse">
          <div class="navbar-inner">
            <div class="container-fluid">
              <div class="row-fluid">
              <div class="span2">
            </div>
            <div class="span10">
              <ul class="nav">
                <li><%= link_to "Home",  home_path %></li>
                <li><%= link_to "Services", services_path %> </li>
                <li><%= link_to "When Required", required_path %></li>
                <li><%= link_to "Faq", faq_path  %></li>
                <li><%= link_to "About Us", about_path  %></li>
                <li><%= link_to "Articles", articles_path  %></li>
                <li><%= link_to "Contact Us", contact_path  %></li>
              </ul>
            </div>
           
          </div><!--.row-fluie -->
          </div>
        </div><!-- /.navbar -->
     

          
          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lnag="en">
<head>
   <meta http-equip="Content-Type" content="text/html; charset=uft- 8"/>
  <title>CFO Support</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable = no">
  <link rel="stylesheet" href="css/normalize.css" type="text/css" media="screen">
  <!-- Bootstrap -->
  <!-- Le style -->
  <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
  <style type="text/css">
  body {
    
  	padding-top: 70px;
  	padding-bottom: 40px;
  }
  
  @media(max-width: 980px) {
  /* Enable use of floated navbar text */
  .navbar-text.pull-right {
  	float: none;
  	padding-left: 5px;
  	padding-right: 5px;

  	}
  }
  </style>
  <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">
   <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
</head>
<body>
  <div class="container-fluid">

	 <%= render 'layouts/header' %>
  </div>
   
<%= yield %>



     <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/javascripts/jquery.js"></script>
    <script src="../assets/javascripts/demo.js"></script>
    <script src="../assets/javascripts/bootstrap-transition.js"></script>
    <script src="../assets/javascripts/bootstrap-alert.js"></script>
    <script src="../assets/javascripts/bootstrap-modal.js"></script>
    <script src="../assets/javascripts/bootstrap-dropdown.js"></script>
    <script src="../assets/javascripts/bootstrap-scrollspy.js"></script>
    <script src="../assets/javascripts/bootstrap-tab.js"></script>
    <script src="../assets/javascripts/bootstrap-tooltip.js"></script>
    <script src="../assets/javascripts/bootstrap-popover.js"></script>
    <script src="../assets/javascripts/bootstrap-button.js"></script>
    <script src="../assets/javascripts/bootstrap-collapse.js"></script>
    <script src="../assets/javascripts/bootstrap-carousel.js"></script>
    <script src="../assets/javascripts/bootstrap-typeahead.js"></script>

  <!-- Analytics
    ================================================== -->
    

   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>




</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/about.html.erb
<div class="container-fluid">
     
      <div class="row-fluid">
        <div class="span12">        
        </div>    
      <div class="row-fluid">        
          <div class="span2">           
          </div>   
          <div class="span6">
          	<div class="unit">

<h1>Biography</h1>
<p>R.B.Warang C.A. founded CFO Support in 2012 with the idea that large sized companies are not the only companies that can benefit from experienced financial professionals. He recognized that the impact of a single, critical decision can be more significant for a smaller and medium sized company than for a larger one. CFO Support fillsl the role of CFO for smaller and medium sized companies, giving them a level of financial management expertise that they are not prepared to hire any CFO on a full-time basis.</p>

<p>R.B.Warang has set a high standard for the level of expertise, skill and experience. His 25 years of experience begin with 12 years experience in medium sized Group in Gulf. Those early years provided a unique combination of experiences with accounting, a very fundamental business approach to serving Group's business units, and the opportunity to work in and learn about many different unit companies in many different industries. This Group taught its employees first to be business and compercial people, and second to be accountants. That training helped develop an understanding of the factors that help a business to succeed.</p>

<p>From that Group, R.B.Warang moved to another reputed private Group where he continued his business education in both small and medium scaled around 25 companies in a broad range of industries including manufacturing, industrial processing, consumer products, and consumer services. He has been Group Finance Manager, GFC for the 2 Groups he worked for. This is typical of the experience and expertise you can expect from your CFO Support.</p>




</div>
 </div>
 <div class="row-fluid">
        <div class="span12">        
        </div>  


        <div class="container-fluid">    
<footer>
  <div class="row-fluid">

   <hr>
    <div class="span3">

    </div>
    <div class="span9">


        <p>&copy; Company 2013</p>
      </footer>
</div>
    </div><!--/.fluid-container-->

app/views/welcome/home.html.erb
    <div class="container-fluid">
     
      <div class="row-fluid">
        <div class="span12">
        
        </div>    
      <div class="row-fluid">        
          <div class="span2">           
          </div>
          <div id="cfogon"  class="span6">                        
                 <div class="side-a">   
               <%= link_to image_tag("cfogon.jpg", alt: "") %>
                </div>              
           </div> 
          <div class="span3">              
                <%= link_to image_tag("supportn.jpg", alt: "") %>              
            </div>           
      </div>
      <div class="row-fluid">
        <div class="span12">
        
        </div> 
        <div class="row-fluid">    
      
          <div class="span2">
          </div>
          <div class="span6">
                <div class="box">
            CFO Advisory Support is a strategic 'CFO' services provider company - and we are based in Mulund East Mumbai. We provide expert finance advisory support to our clients. We can take care of the Financial Management of Small and Medium Scale Enterprises at the affordable cost. We porvide financial guidence without cost of hiring a full time highly paid <stong>CFO </stong>. We can help our client' company to be more profitable and successful and assist to take the company's business to next higher level.
                </div>
          </div>
          <div class="span3">   
              <h3>We provide our clients:</h3>
              <div class="accordion" id="accordion2">
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse1">
                  Professional attention
                  </a>
                  </div>
                  <div id="collapse1" class="accordion-body collapse" >
                    <div class="accordion-inner">

                      Our firm is one of a few providing outsourced CFO support. By combining our expertise, experience and enthusiasm, every client receives close personal and professional attention. CFO support is committed to providing the highest level of service. We achieve this by ensuring that each and every client is served by the expertise of our firm and this attitude makes us a sound business partner.
                      </div>
                  </div>
                </div> 
                <div class="accordion" id="accordion2">
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse2">                     
                    
                      Timely responsiveness
                      </a>
                  </div>
                  <div id="collapse2" class="accordion-body collapse" >
                    <div class="accordion-inner">
               
                      Companies and individuals who choose CFO Support rely on our competent advice in a timely manner. Though we take time to get to know our clients, their needs, and time constraints. We respond to our clients' need quickly by tailoring our services in order to meet their unique requirements. Responsiveness has earned CFO Support the respect of our clients.
                      </div>
                  </div>
                </div> 
                <div class="accordion" id="accordion2">
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse3">                     
                    
                  
                  Quality Support 
                   </a>
                  </div>
                  <div id="collapse3" class="accordion-body collapse" >
                    <div class="accordion-inner">
                 
                    CFO support reputation has been achieved by a strong commitment to providing the highest level of professional quality support. The role of a trusted advisor is not the one that our firm takes lightly. We consistently strive to provide clients with accurate and insightfull advice so that they are able to make well-informed decisions.
                       </div>
                  </div>
                </div> 

       



                       
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->
</div><!--/.fluid-container-->
 <div class="container-fluid">    
<footer>
  <div class="row-fluid">

   <hr>
    <div class="span3">

    </div>
    <div class="span9">


        <p>&copy; Company 2013</p>
      </footer>
</div>
    </div><!--/.fluid-container-->

app/views/work/articles.html.erb
<h1>Work#articles</h1>
<p>Find me in app/views/work/articles.html.erb</p>

app/views/work/contact.html.erb
<h1>Work#contact</h1>
<p>Find me in app/views/work/contact.html.erb</p>

app/views/work/faq.html.erb
<div class="container-fluid">
     
      <div class="row-fluid">
        <div class="span12">        
        </div>    
      <div class="row-fluid">        
          <div class="span2">           
          </div>   
          <div class="span6">
          	<div  class="faqunit">


<h1>Frequently Aksed Questions</h1>
<p>Question<br>
What would a Expert CFO Support do for my company?</p>
<p>
<div class="ans">Answer</div><br>
It depends on your company's needs. The short answer is that which your own CFO or controller would do. The difference is we have more experience expertise on which to draw, and we only change you when we are there.</p>
<p>Question<br>
Does "EXpert CFO Support" means they are only availabe online or over the phone? What if I need someone onsite?</p>
<p>
	<div class="ans">Answer</div><br>
Expert CFO Support work almost exclusively onsite at the client's location where we can be most effective.</p>

<p>Question<br>
Why do I need a Expert CFO Support if I have a Accountant?</p>
<p>
	<div class="ans">Answer </div><br>
Expert CFO Support are professionals in financial management. That is all we do. Accountants are professionals in financial statement preparation, and auditing. Asking your Accoutant to assist your company in financial management and strategic planning is a little like asking your architect to build your building.</p>

<p>Question<br>
Is having Expert CFO solution expensive?</p>
<p>
	<div class="ans">Answer</div><br>
The idea of having Expert CFO Solutions is that your company only uses him for things that do not occur every day. Your staff is (or should be) able to handle day-to-day activity. (see our list of services on this website for area in which Expert CFO Solutions can be used most effectively. For these areas you should be looking for quality financial management, not quantity. One key decision based on the right information can make all the difference to your company.) Expert CFO Support Solutions only works for you when you need him. It might be a day a week or a month. The cost at a day or a week is less than half of the cost of a full-time Financial Controller.</p>

<p>Question<br>
What if I don't think I need a Expert CFO Support every week? What if I just have a project I need completed?</p>
<p>
	<div class="ans">Answer</div><br>
Expert CFO Support will complete the Projects - your staff cannot.</p>


</div>
 </div>
 <div class="row-fluid">
        <div class="span12">        
        </div>  


        <div class="container-fluid">    
<footer>
  <div class="row-fluid">

   <hr>
    <div class="span3">

    </div>
    <div class="span9">


        <p>&copy; Company 2013</p>
      </footer>
</div>
    </div><!--/.fluid-container-->

app/views/work/required.html.erb
<div class="container-fluid">
     
      <div class="row-fluid">
        <div class="span12">        
        </div>    
      <div class="row-fluid">        
          <div class="span2">           
          </div>   
          <div class="span6">
          	<div class="unit">
          <h3>When our services required by our clients</h3>

<ul id="req">
	<li>When you think your company should be more profitable</li>
	<li>When you need assistance with strategic planning</li>
	<li>When you feel that you could benefit from an experienced financial consultants for discussing ideas</li>
	<li>When you could use some meaningful financial analysis</li>
	<li>When your financial systems do not produce timely and accurate information for reporting purposes and decision making</li>
	<li>When you are spending too much time managing the finance/accounting function.</li>
	<li>When your systems that measure operations performance do not produce timely and accurate statistic for the purpose of making informed decisions</li>
	<li>When you are not absolutely certain which factors are most important in driving (or limiting) the growth and profitablily of your company; how those should be tracked and analyzed; how they should affect your strategy.</li>
	<li>When you feel like your organization may not be structured in the best way to facilitate growth and efficient operation.</li>
	<li>When your business is growing and you don't have a growth plan.</li>
	<li>When you want to develop an effective incentive compensation program to help drive performacne and avoid expensive turnover.</li>
	<li>When you need projections of cash flow, profits, growth and impact of outside economic factors.</li>
	<li>When your policies, procedures and internal controls seem loose and you know you need to tighten them</li>
	<li>When you would like access to someone who can negotiate with bankers, vendors, regulators, customers, unioons or other outside parties.</li>
	<li>When your financial staff could use guidence and training.</li>
	<li>When you would like help identifying risks and opportunities.</li>
</ul>
</div>
 </div>
 <div   id="box" class="span3">
 </div>

 <div id="supportre" class="span3">   
 <%= link_to image_tag("supportnn.jpg", alt: "") %>
</div>

</div>
 <div   id="box1" class="span3">
 </div>
                 

 <div class="row-fluid">
        <div class="span12">  


                  
      
        </div>  


        <div class="container-fluid">    
<footer>
  <div class="row-fluid">

   <hr>
    <div class="span3">

    </div>
    <div class="span9">


        <p>&copy; Company 2013</p>
      </footer>
</div>
    </div><!--/.fluid-container-->